version: 2

models:
  - name: stg_blocks
    description: "Standardized Ethereum blocks data"
    columns:
      - name: block_hash
        description: "Unique identifier for the block (primary key)"
        tests:
          - unique
          - not_null
      - name: block_number
        description: "Block number as string"
        tests:
          - not_null
      - name: block_number_int
        description: "Block number as integer"
        tests:
          - not_null
      - name: block_timestamp
        description: "Block timestamp as datetime"
        tests:
          - not_null
      - name: parent_hash
        description: "Hash of the parent block"
        tests:
          - not_null