name: dbt CI

on:
  pull_request:
    branches: [ main ]          # watch PRs targeting main
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}  
  cancel-in-progress: true                       

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Tell dbt where the repo-scoped profiles.yml lives
      DBT_PROFILES_DIR: .
      # Inject warehouse secrets from Settings → Secrets → Actions
      CLICKHOUSE_DEV_PASSWORD: ${{ secrets.CLICKHOUSE_DEV_PASSWORD }}
      CLICKHOUSE_DEV_HOST: ${{ secrets.CLICKHOUSE_DEV_HOST }}
      CLICKHOUSE_DEV_USER: ${{ secrets.CLICKHOUSE_DEV_USER }}
      CLICKHOUSE_DEV_PORT: ${{ secrets.CLICKHOUSE_DEV_PORT }}
      CLICKHOUSE_DEV_SCHEMA: ${{ secrets.CLICKHOUSE_DEV_SCHEMA }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with: { python-version: '3.13' }

      - name: Install dbt + linter
        run: |
          pip install "dbt-core" "dbt-clickhouse" \
                      sqlfluff sqlfluff-templater-dbt
      
      - name: dbt deps
        run: dbt deps  

      - name: SQLFluff lint
        run: sqlfluff lint                                                

      - name: dbt compile
        run: dbt compile --target dev            

      - name: dbt build
        run: dbt build   --target dev

      - name: dbt run  
        run: dbt run   --target dev