name: Publish dbt Docs → GitHub Pages

on:
  workflow_run:
    workflows: ["dbt CI"]        # must exactly match the name above
    branches: [main]             # deploy only after CI on main
    types: [completed]

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages:    write
  id-token: write

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: .
      # same secrets set as in CI (needed only if you ever rebuild docs here)
      CLICKHOUSE_PROD_PASSWORD: ${{ secrets.CLICKHOUSE_PROD_PASSWORD }}
      CLICKHOUSE_PROD_HOST:     ${{ secrets.CLICKHOUSE_PROD_HOST }}
      CLICKHOUSE_PROD_USER:     ${{ secrets.CLICKHOUSE_PROD_USER }}
      CLICKHOUSE_PROD_PORT:     ${{ secrets.CLICKHOUSE_PROD_PORT }}
      CLICKHOUSE_PROD_SCHEMA:   ${{ secrets.CLICKHOUSE_PROD_SCHEMA }}

    steps:
      # 1. Download the docs artifact produced by the CI run
      - uses: actions/download-artifact@v4
        with:
          name: dbt-docs
          run-id: ${{ github.event.workflow_run.id }}
          path: ./site                   

      # 2. Publish to GitHub Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - uses: actions/deploy-pages@v2
