name: dbt CI

on:
    push:
      branches: [ main ]          # every merge → deployment
    workflow_dispatch: {}         # allow manual runs

    schedule:
        - cron: '*/15 * * * *' # Runs every 15 minutes
concurrency:
  group: ci-${{ github.head_ref || github.ref }}  
  cancel-in-progress: true                       

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Tell dbt where the repo-scoped profiles.yml lives
      DBT_PROFILES_DIR: .
      # Inject warehouse secrets from Settings → Secrets → Actions
      CLICKHOUSE_PROD_PASSWORD: ${{ secrets.CLICKHOUSE_PROD_PASSWORD }}
      CLICKHOUSE_PROD_HOST: ${{ secrets.CLICKHOUSE_PROD_HOST }}
      CLICKHOUSE_PROD_USER: ${{ secrets.CLICKHOUSE_PROD_USER }}
      CLICKHOUSE_PROD_PORT: ${{ secrets.CLICKHOUSE_PROD_PORT }}
      CLICKHOUSE_PROD_SCHEMA: ${{ secrets.CLICKHOUSE_PROD_SCHEMA }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with: { python-version: '3.13' }

      - name: Install dbt + linter
        run: |
          pip install "dbt-core" "dbt-clickhouse" \
                      sqlfluff sqlfluff-templater-dbt
      
      - name: dbt deps
        run: dbt deps  

      # - name: SQLFluff lint
      #   run: sqlfluff lint                                                

      - name: dbt compile
        run: dbt compile --target prod            

      - name: dbt build
        run: dbt build   --target prod

      - name: dbt run
        run: dbt run   --target prod
